"""remove_filesystem_resource_columns

Revision ID: 62500b9dae7b
Revises: 9cfb371853dc
Create Date: 2026-03-11 07:58:57.669006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62500b9dae7b'
down_revision: Union[str, None] = '9cfb371853dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'custom_slash_commands')
    op.drop_column('user_settings', 'custom_agents')
    op.drop_column('user_settings', 'custom_skills')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('custom_skills', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('user_settings', sa.Column('custom_agents', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('user_settings', sa.Column('custom_slash_commands', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
